version: '3'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: "senha"
      MYSQL_DATABASE: "database"
    ports:
      - "3308:3306"
volumes: 
  mysql-compose-network:
    driver: local